function getContextPath(){return window.location.pathname.substring(0,window.location.pathname.indexOf("/",2))}
function coachSearch(){$("#loader").removeClass("loaded"),$("form[id=coachSearch]").submit(function(e){return!1});var e=getContextPath()+"/coaches?searchTerm="+$("#searchTerm").val()+"&postalCode="+$("#postalCode").val()+"&distance="+$("#distance").val();$.ajax({type:"POST",url:e,success:function(a){$("#loader").addClass("loaded"),$(".coach-list").html(a),window.history.pushState("data","Title",e)},error:function(){$("#errorDiv").html("An Error Occurred while searching")},})}
function applyFilter(e,a){if(a.checked){$("#loader").removeClass("loaded");var t=getUrlToCall(e);$.ajax({type:"POST",url:t,success:function(e){$("#loader").addClass("loaded"),$(".coach-listst").html(e),window.history.pushState("data","Title",t)},error:function(){$("#loader").addClass("loaded"),$(".alert-danger").show(),setTimeout("$('.alert-danger').fadeOut(); ",4e3)},})}else clearFilter(e)}
function clearTopFilter(e){$("#loader").removeClass("loaded");var a=e.split(":");clearFilter(a[0].trim()+":"+a[1].trim())}
function clearFilter(e){var a=getUrlParameter("numItemsPerPage"),t=getUrlParameter("sort"),l="",r=getUrlParameter("filter").split("::");for(i=0;i<r.length;i++)
if(r[i].includes(" AND ")){var o=r[i].split(":")[0],c=r[i].split(":")[1].split(" AND "),n="";for(k=0;k<c.length;k++)o+":"+c[k]!=e&&(n=n.concat(c[k]).concat(" AND "));" AND "==n.substr(n.length-5)&&(n=n.slice(0,-5)),(l=l.concat(o+":"+n)),i!=r.length-1&&(l=l.concat("::"))}else r[i]!=e&&((l=l.concat(r[i])),i!=r.length-1&&(l=l.concat("::")));if((":"==l.charAt(l.length-1)&&(l=l.slice(0,-2)),null==l||""==l))var s=paginateURLToCall(null,"1",a,t);else s=paginateURLToCall(l,"1",a,t);$.ajax({type:"POST",url:s,success:function(e){$("#loader").addClass("loaded"),$(".coach-list").html(e),window.history.pushState("data","Title",s)},error:function(){$("#loader").addClass("loaded"),$(".alert-danger").show(),setTimeout("$('.alert-danger').fadeOut(); ",4e3)},})}
function paginate(e,a,t){$("#loader").removeClass("loaded");var l=paginateURLToCall(getUrlParameter("filter"),e,a,t);$.ajax({type:"POST",url:l,success:function(e){$("#loader").addClass("loaded"),$(".coach-list").html(e),window.history.pushState("data","Title",l)},error:function(){$("#loader").addClass("loaded"),$(".alert-danger").show(),setTimeout("$('.alert-danger').fadeOut(); ",4e3)},})}
function paginateURLToCall(e,a,t,l){var r=getContextPath()+"/coaches?searchTerm="+getUrlParameter("searchTerm")+"&postalCode="+getUrlParameter("postalCode")+"&distance="+getUrlParameter("distance");return null!=e&&(r=r+"&filter="+e),null!=a&&(r=r.concat("&pageNum=").concat(a)),null!=t&&(r=r.concat("&numItemsPerPage=").concat(t)),null!=l&&(r=r.concat("&sort=").concat(l)),r}
function getUrlParameter(e){(url=window.location.href),(e=e.replace(/[\[\]]/g,"\\$&"));var a=new RegExp("[?&]"+e+"(=([^&#]*)|&|#|$)").exec(url);return a?(a[2]?decodeURIComponent(a[2].replace(/\+/g," ")):""):null}
function getUrlToCall(e){var a=getUrlParameter("searchTerm"),t=getUrlParameter("postalCode"),l=getUrlParameter("distance"),r=getUrlParameter("numItemsPerPage"),o=getUrlParameter("sort"),c=getUrlParameter("filter"),n="";if(null!=c){var s=[],d=c.split("::");for(i=0;i<d.length;i++)s.push(d[i].split(":")[0]);if(s.includes(e.split(":")[0]))
for(i=0;i<d.length;i++){var u=d[i].split(":")[0],g=d[i].split(":")[1],m=e.split(":")[0],h=e.split(":")[1];if(u==m){if(!g.split(" AND ").includes(h)){var p=d[i].split(":")[1].concat(" AND ").concat(e.split(":")[1]);n=n.concat(m.concat(":").concat(p))}}else n=n.concat(d[i]);i!=d.length-1&&(n=n.concat("::"))}else n=c.concat("::").concat(e)}else n=e;var f=getContextPath()+"/coaches";return(null!=a&&(f=f.concat("?searchTerm=").concat(a)),null!=t&&(f=f.concat("&postalCode=").concat(t)),null!=l&&(f=f.concat("&distance=").concat(l)),(f=(f=f.concat("&filter=").concat(n)).concat("&pageNum=").concat("1")),null!=r&&(f=f.concat("&numItemsPerPage=").concat(r)),null!=o&&(f=f.concat("&sort=").concat(o)),f)}
function clearAll(){$("#loader").removeClass("loaded");var e=paginateURLToCall(null,"1",getUrlParameter("numItemsPerPage"),getUrlParameter("sort"));$.ajax({type:"POST",url:e,success:function(a){$("#loader").addClass("loaded"),$(".coach-list").html(a),window.history.pushState("data","Title",e)},error:function(){$("#loader").addClass("loaded"),$(".alert-danger").show(),setTimeout("$('.alert-danger').fadeOut(); ",4e3)},})}